### PR TITLE
Add release metadata, Update developer name

### PR DESCRIPTION
**Pull request by noonsleeper**

### CODE REVIEW

**Review by daiyam — APPROVED** [review]
LGTM

**Comment by daiyam** [comment]
Can the addition a the new `release` be automated?

Thx I forgot about it....

**Comment by noonsleeper** [comment]
> Can the addition of the new `release` be automated?

`flatpak-external-data-checker` does not have that capacity.
But I forked vscodium repo long time ago and start to work on that, the idea is populating the `com.vscodium.codium-insiders.metainfo.xml` directly from upstream since is useful to any distribution, but my free time now is more scarce sadly

**Comment by daiyam** [comment]
Do you or flathub run `flatpak-external-data-checker`? Can you disable it?
If you can, I can automate the creation of the PR directly from VSCodium workflow. (So you won't need to edit the `com.vscodium.codium-insiders.metainfo.xml` each time)

**Comment by noonsleeper** [comment]
We can disable it but will be better to maintain it since we have a couple of dependencies that the checker looks like host-spawn, ide-flatpak-wrapper and libsecret, I think the better is to move `com.vscodium.codium-insiders.metainfo.xml` onto upstream and let the checker update the package here, it's also expected by the flathub team that someone test the app before merge to `master` and not do a complete automation of the process or at least that is often discussed on the matrix chat room

**Comment by daiyam** [comment]
> I think the better is to move `com.vscodium.codium-insiders.metainfo.xml` onto upstream

Do you mean in, for example, `https://github.com/VSCodium/vscodium/tree/master/stores/flathub`?

> that someone test the app before merge to `master` and not do a complete automation of the process

Ok so I leave you do the merges.

**Comment by noonsleeper** [comment]
> Do you mean in, for example, `https://github.com/VSCodium/vscodium/tree/master/stores/flathub`?

That metainfo file is part of https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

> Ok so I leave you do the merges.

Understandable ;)

When I take some vacations I will try to make some progress on automate the metainfo.xml on upstream =)
Like always, thanks for your patient

**Pull request merged**
